#!/usr/bin/env python3
"""Generate the z88dk z80asm export from the canonical SjASMPlus sources."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "libman"
OUTPUT_DIR = SOURCE_DIR / "z80asm"
SOURCE_NAMES = (
    "libman.asm",
    "libman13.asm",
    "libman_core.inc",
    "libman_core13.asm",
    "libman_state.inc",
)

GENERATED_HEADER = """; Generated by scripts/export_z80asm.py; do not edit.
; Source of truth: the sibling canonical SjASMPlus export.
"""


def translate(text: str) -> str:
    lines: list[str] = []
    skip_legacy_aliases = False

    for line in text.splitlines():
        stripped = line.strip()

        if stripped == "IFNDEF  LIBMAN_NO_LEGACY_API":
            skip_legacy_aliases = True
            continue
        if skip_legacy_aliases:
            if stripped == "ENDIF":
                skip_legacy_aliases = False
            continue

        if re.fullmatch(r"MODULE\s+LIBMAN", stripped, re.IGNORECASE):
            continue
        if stripped.upper() == "ENDMODULE":
            continue

        match = re.match(
            r"^(\s*)DEFINE\s+([A-Za-z_][A-Za-z0-9_]*)(?:\s+(.+?))?\s*$",
            line,
            re.IGNORECASE,
        )
        if match:
            indent, name, value = match.groups()
            lines.append(f"{indent}defc    {name} = {value or '1'}")
            continue

        translated = line.replace("LIBMAN.", "")
        for char in ("L", "1", "0", "2"):
            translated = translated.replace(f'"{char}"', f"'{char}'")
        translated = translated.replace("'\\'", "5Ch")
        lines.append(translated)

    return GENERATED_HEADER + "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT_DIR.mkdir(exist_ok=True)
    for name in SOURCE_NAMES:
        source = SOURCE_DIR / name
        output = OUTPUT_DIR / name
        output.write_text(translate(source.read_text(encoding="utf-8")), encoding="utf-8")


if __name__ == "__main__":
    main()
