; Generated by scripts/export_z80asm.py; do not edit.
; Source of truth: the sibling canonical SjASMPlus export.
; Последняя редакция: 30.04.2004
;
; Module LIBMAN v1.3
;
; Доработанный менеджер dll-библиотек, версия v1.3.
; (на 48 байт короче оригинального).
;
; Менеджер работает с форматами L0, L1 библиотек.
;
;
;
; Примечание:
; ~~~~~~~~~~~
; формат "L0":
;   4 нуля (32 бита) перед таблицей перемещений нужны для того,
;   чтобы функция remake "обошла" 32 байта dll-заголовка.
;



; Экспортная версия собирается двумя частями:
;   LIBMAN_LOADER_ONLY  - загрузчик, пригодный для размещения в WIN0;
;   LIBMAN_RUNTIME_ONLY - call/free/info и relocation, размещаемые вместе
;                         с состоянием в постоянно видимом WIN1.

	IFNDEF	LIBMAN_RUNTIME_ONLY

true	equ	1
false	equ	0

	IFNDEF	LIBMAN_MAX_LIBS
	defc    LIBMAN_MAX_LIBS = 64
	ENDIF
	ASSERT	LIBMAN_MAX_LIBS >= 1
	ASSERT	LIBMAN_MAX_LIBS <= 64

; В split-режиме эта точка и _L_LOAD могут находиться в WIN0.
coreload equ	_L_LOAD


;==================================================================
;  Таблица загрузки библиотек (LIBMAN_MAX_LIBS, макс. 64 шт.)
;==================================================================
; Размер таблицы: LIBMAN_MAX_LIBS * 4 байта
; Макс. число элементов: 64
; Длина элемента: 4 байта
; Структура отдельного элемента таблицы:
;
;    +00  - 0/1 свободен/занят
;    +01  - дескр. блока памяти
;    +02  - ст.байт адреса начала
;    +03  - ст.байт адреса конца

max_count equ	LIBMAN_MAX_LIBS		; макс. число загр. библиотек




;==================================================================
;  Загрузка библиотеки в память
;==================================================================
;   ld      hl,filename   ;имя файла
;   ld      a,win         ;окно 1,2,3
;   call    l_load
;   jp      c,error
;   ld      (handle),hl   ;дескр. библы
;
_L_LOAD:
	push	ix
	push	iy
	push	de
	push    af
	push    hl
	xor	a
	ld	(ll_tmp_owned),a
	ld	(ll_final_new),a
	IFNDEF	LIBMAN_L2_ONLY
	ld	(llzero+1),a
	IFNDEF	LIBMAN_L0_L1_ONLY
	ld	(ll2_active+1),a	; флаг "это L2"
	ENDIF
	ENDIF
	ld	a,true
	ld	(ll_fr+1),a		; флаг релокации
	IFNDEF	LIBMAN_L2_ONLY
	ld	(ll_fc+1),a		; флаг компрессии
	ENDIF
	in      a,(0E2h)
	ld      (lloldw+1),a		; сохр. начальную Page3
	IFDEF	LIBMAN_TEST_LOAD_FAILURE_HOOK
	; Test-only fault injection runs after the unwind state is initialized.
	call	LIBMAN_TEST_LOAD_FAILURE_HOOK
	jp	c,llerr_before_path
	ENDIF
	; выделить блок в 2 страницы.  L2 не распаковывается и само по себе не
	; нуждалось бы во 2-й странице, но она нужна как раз для того, чтобы
	; ll_l2_finish мог переключаться на неё через тот же индекс страницы
	; (1), что доказанно работает у L0/L1 (см. ll10) -- см. docs/l2_plan.md
	; про то, почему временная страница у L2 не может использовать индекс 0.
	IFDEF	LIBMAN_DIAGNOSTICS
	ld	a,LS_TEMP_ALLOC
	ld	(ll_load_stage_active),a
	ENDIF
	ld      bc,023Dh
	rst     10h
	jp      c,llerr_dss_before_path	; ошибка выделения
	ld      (llid),a		; дескр. выдел. блока памяти
	ld	a,true
	ld	(ll_tmp_owned),a
	; сразу подготовить одну страницу
	; под загрузку файла библы.
	IFDEF	LIBMAN_DIAGNOSTICS
	ld	a,LS_TEMP_MAP
	ld	(ll_load_stage_active),a
	ENDIF
	ld      bc,003Bh		; подкл. 1-ю страницу блока в 3-е окно
	ld	a,(llid)
	rst     10h
	jp      c,llerr_dss_before_path	; ошибка подключения
	pop     hl
	IFDEF	LIBMAN_DIAGNOSTICS
	ld	a,LS_OPEN
	ld	(ll_load_stage_active),a
	ENDIF
	call	ll_select_path
	jr	nc,ll_path_selected
	ld	a,LR_OPEN
	ld	(l_reason),a
	jp	llerr_no_file_after_path
ll_path_selected:
	ld      (llhand),a		; дескр. открытой библы
	; указатель в конец файла
	IFDEF	LIBMAN_DIAGNOSTICS
	ld	a,LS_IO
	ld	(ll_load_stage_active),a
	ENDIF
	ld      hl,0
	push	hl
	pop	ix
	; Ownership bookkeeping above clobbers A; MOVE_FP needs the open handle.
	ld	a,(llhand)
	ld      bc,0215h		; MOVE_FP
	rst     10h
	jp      c,llerr_dss_after_path	; ошибка перемещения указателя
	IFDEF	LIBMAN_DIAGNOSTICS
	ld	a,LS_FORMAT
	ld	(ll_load_stage_active),a
	ENDIF
	ld      a,h
	or      l
	jr	z,ll_eof_size_ready
	; llsize is used only to prove that the <=16 KiB prefix fits in the
	; physical file.  Saturation is enough when the DSS 32-bit size exceeds
	; 65535 bytes and avoids imposing that limit on a trailing payload.
	ld	ix,0FFFFh
ll_eof_size_ready:
	push    ix			; размер файла, мл.разряд
	; вернуть указатель в начало файла
	ld      hl,0
	push	hl
	pop	ix
	ld      a,(llhand)		; дескр. открытой библы
	ld      bc,0015h		; MOVE_FP
	rst     10h
	pop     hl
	ld      (llsize),hl		; размер библы
	IFDEF	LIBMAN_CALL_TRACE
	ld	(l_trace_load_size),hl
	ENDIF
	jp      c,llerr_dss_after_path	; ошибка перемещения указателя
	; чтение файла
	ld      c,13h
	ld      de,16			; число чит. байт
	ld      hl,llbuf		; буфер первых 16-ти байт заголовка
	ld      a,(llhand)		; дескр. открытой библы
	rst     10h
	jp      c,llerr_dss_after_path
	; вернуться в начало файла
	ld      hl,0
	push	hl
	pop	ix
	ld      a,(llhand)		; дескр. открытой библы
	ld      bc,0015h		; MOVE_FP
	rst     10h
	jp      c,llerr_dss_after_path	; ошибка перемещения указателя
	; берем данные из первых 16-ти байт заголовка
	IFDEF	LIBMAN_DIAGNOSTICS
	ld	a,LS_FORMAT
	ld	(ll_load_stage_active),a
	ENDIF
	ld	ix,llbuf		; буфер первых 16-ти байт заголовка
	ld	a,(ix+0)
	cp	'L'
	jp	nz,llerr_after_path	; не знакомый формат библы
	ld	a,(ix+1)
	cp	'2'
	IFDEF	LIBMAN_L0_L1_ONLY
	jp	z,llerr_after_path	; L2 в этой сборке не поддержан
	ELSE
	jp	z,ll_l2_entry
	ENDIF
	IFDEF	LIBMAN_L2_ONLY
	jp	llerr_after_path	; в этой сборке валиден только "L2"
	ELSE
	ld	e,true
	cp	'1'
	jr	z,ll0s
	cp	'0'
	jp	nz,llerr_after_path	; не верный формат библы
	dec	e
ll0s:	ld	a,e
	ld	(l1_form+1),a		; true/false  уст. формат библы
	ld      e,(ix+2)		; общ. размер библы (de идет для функ.чтения)
	ld      d,(ix+3)
	ld	l,(ix+4)		; размер библы без рел-таблицы
	ld	h,(ix+5)
	ld	c,(ix+6)		; размер рел-таблицы
	ld	b,(ix+7)
	; Validate the canonical output before decoding into the 16 KiB scratch
	; page.  In particular, reject 16-bit addition overflow.
	ld	a,l
	sub	32
	ld	a,h
	sbc	a,0
	jp	c,llerr_after_path
	; библа сжата ? (de=hl ?)
	add	hl,bc			; заголовок + код библы = размер библы
	jp	c,llerr_after_path
	ld	a,h
	cp	40h
	jr	c,ll_image_size_ok
	sub	40h
	or	l
	jp	nz,llerr_after_path
ll_image_size_ok:
	ld	a,h
	cp	d
	jr	nz,ll0r			; сжата
	ld	a,l
	cp	e
	jr	nz,ll0r			; сжата
	xor	a			; false
	ld	(ll_fc+1),a		; сбр. флаг компрессии (библа не сжата)
	; библа перемещаемая ?
ll0r:	ld	a,b
	or	c
	jr	nz,ll_reloc_ready	; да, рел-таблица не равна нулю
	ld	(ll_fr+1),a		; сбр. флаг релокации
ll_reloc_ready:
	ld	a,h
	add	a,0C0h
	ld	h,a
	ld	(lloutend+1),hl		; exact expected end of decoded image
	; The prefix is the only portion libman loads.  Bytes physically after it
	; are an optional library payload for INIT, so validate the prefix against
	; the measured file length before reusing llsize as the remaining input.
	ld	a,d
	cp	40h
	jr	c,ll_prefix_page_ok
	sub	40h
	or	e
	jp	nz,llerr_after_path
ll_prefix_page_ok:
	ld	a,e
	sub	16
	ld	a,d
	sbc	a,0
	jp	c,llerr_after_path
	ld	hl,(llsize)		; physical file size from MOVE_FP
	or	a
	sbc	hl,de
	jp	c,llerr_after_path	; truncated prefix
	ld	(llsize),de		; packed bytes remaining to copy/decode
	; Read exactly the prefix; the file pointer is then at the trailing payload.
	; de=loaded prefix size
ll0:	ld      c,13h
	ld      hl,0C000h		; буфер чтения
	ld      a,(llhand)		; дескр. библы
	rst     10h
	jp      c,llerr_dss_after_path	; ошибка чтения
	IFDEF	LIBMAN_CALL_TRACE
	ld	a,(0C104h)
	ld	(l_trace_bitmap_raw),a
	ENDIF
	IFDEF	LIBMAN_DIAGNOSTICS
	ld	a,LS_COPY
	ld	(ll_load_stage_active),a
	ENDIF
	;
	ld      hl,0C000h		; начало 0-й страницы
	ld      d,h			; также для 1-й страницы
	ld      e,l
	; hl - упак. данные в 0-й странице
	; de - распак. данные в 1-й странице
	; llsize - packed bytes remaining (the final chunk may be shorter than 16)
loop:	ld	bc,16
	ld	a,(llsize+1)
	or	a
	jr	nz,ll_chunk_ready
	ld	a,(llsize)
	cp	c
	jr	nc,ll_chunk_ready
	ld	c,a
ll_chunk_ready:
	; SET_BUFFER samples only the immediate operand of the following LD A,n.
	; Patch both accelerator copies before selecting the command.
	ld	a,c
	ld	(ll_copy_in_size+1),a
	ld	(ll_copy_out_size+1),a
	push    de
	ld      de,llbuf		; исп. буфер первых 16-ти байт заголовка
	; аксель
	di
	ld      d,d			; вкл. аксель на уст. размера блока
ll_copy_in_size:
	ld      a,16			; размер буфера (self-modified for the final chunk)
	ld      b,b			; выкл. аксель
	ld      l,l			; копир. блока
	ld      a,(hl)			;
	ld      (de),a			;
	ld      b,b			; выкл. аксель
	ei
	add     hl,bc
	push    hl
	; The source pointer is saved, so HL is free for the remaining byte count.
	ld	hl,(llsize)
	or	a
	sbc	hl,bc
	ld	(llsize),hl
	push    bc
	ld      a,(llid)		; дескр. выдел. блока из 2-х страниц
	ld      bc,013Bh		; подкл. 2-ю страницу блока в 3-е окно
	rst     10h
	pop     bc
	pop     hl
	pop     de
	jp      c,llerr_dss_after_path	; ошибка подкл.
	push    hl
	ld      hl,llbuf		; буфер первых 16-ти байт заголовка
ll_fc:	ld	a,true			; флаг компрессии
	or	a
	jr	z,ll1z			; не было компрессии
	; de == 0C010h ?
	ld      a,d
	cp      0C0h			; ст.байт начала страницы
	jr      nz,ll2
	ld      a,e
	cp      10h			; размер блока
	jr      nc,ll2
	; аксель
ll1z:	di
	ld      d,d			; вкл. аксель на уст. размера блока
ll_copy_out_size:
	ld      a,16			; размер буфера (self-modified for the final chunk)
	ld      b,b			; выкл. аксель
	ld      l,l			; копир. блока
	ld      a,(hl)			;
	ld      (de),a			;
	ld      b,b			; выкл. аксель
	ei
	ex      de,hl
	add     hl,bc			; de+ for simple copy
	ex      de,hl
	jr      ll3
;-
ll2:	ld	b,c			; b=16
llzero:	ld      a,false			; флаг последовательности нулей
	or      a
	jr      z,ll2a			; false
	xor     a
	ld      (llzero+1),a
	jr      ll2c
	;
ll2a:	ld	a,d
	or	a
	jp	z,ll_decode_error	; decoded output wrapped out of WIN3
	ld      a,(hl)
	or      a
	jr      nz,ll2b
	inc     hl
	dec     b
	jr      z,ll2e
ll2c:	ld      (de),a
	inc	e			; de++ with a boundary check only on page wrap
	jr	nz,llzero_count
	inc	d
	jr	z,llzero_boundary
llzero_count:
	dec     (hl)
	jr      nz,ll2c
llzero_done:
	inc     hl
	jr      ll2d
llzero_boundary:
	dec	(hl)
	jp	nz,ll_decode_error	; zero run would continue into WIN0
	jr	llzero_done
	;
ll2e:	ld      a,true
	ld      (llzero+1),a		; флаг последовательности нулей
	jr      ll3
	;
ll2b:	ld      (de),a
	inc     hl
	inc     de
ll2d:	djnz	ll2a
;-
ll3:	push    de
	ld      a,(llid)		; дескр. выдел. блока из 2-х страниц
	ld      bc,003Bh		; подкл. 1-ю страницу блока в 3-е окно
	rst     10h
	pop     de
	pop     hl			; hl=0C010h ?
	jp	c,llerr_dss_after_path	; ошибка подкл.
	ld	a,(llsize+1)
	ld	b,a
	ld	a,(llsize)
	or	b
	jp	nz,loop			; назад, пока не исчерпан prefix
	ld	a,(llzero+1)
	or	a
	jp	nz,llerr_after_path	; prefix ended between RLE marker and count
	;
ll4:
	IFDEF	LIBMAN_CALL_TRACE
	push	hl
	ENDIF
lloutend:
	ld	hl,0
	or	a
	sbc	hl,de
	IFDEF	LIBMAN_CALL_TRACE
	pop	hl
	ENDIF
	jp	nz,llerr_after_path	; truncated or overlong RLE output
	IFDEF	LIBMAN_CALL_TRACE
	ld	(l_trace_copy_source_end),hl
	ld	(l_trace_copy_dest_end),de
	ENDIF
	ld      a,(llid)		; дескр. выдел. блока из 2-х страниц
	ld      bc,013Bh		; подкл. 2-ю страницу в 3-е окно
	rst     10h
	jp	c,llerr_dss_after_path
	IFDEF	LIBMAN_CALL_TRACE
	ld	a,(0C104h)
	ld	(l_trace_bitmap_staged),a
	ENDIF
	ld      hl,0C004h		; +4 адрес начала рел-таблицы (заголовок)
	ld      e,(hl)
	inc     hl
	ld      d,(hl)
	inc     hl
	ex      de,hl
	dec     hl
	ld	a,(ll_fr+1)		; флаг релокации
	or	a
	jr	nz,ll4a
	; библа была не перемещаемая (без рел-таблицы).  3FFFh -- инклюзивный
	; конец страницы, как и у L2 (см. ll2_relocatable): 4000h завернул бы
	; (ix+3) через 100h при подселении на свежую страницу, а вместе с
	; guard'ом выше в ll10 сделал бы цикл копирования бесконечным вместо
	; безобидного усечения до 256 байт.
	ld	hl,3FFFh		; макс. размер не перемещ. библы
	ENDIF

; ll_fr must stay defined when the L0/L1 block above is stripped out: the L2
; path reads the flag through (ll_fr+1).  In the full build the non-relocatable
; L0/L1 branch above still falls through this LD as code, exactly as in libman
; 1.3; A is dead until ll4a reloads it.
ll_fr:	ld	a,true			; флаг релокации
ll4a:	ld      (llsize),hl		; размер библы (код)
	ld      a,(llid)		; дескр. выдел. блока из 2-х страниц
	ld      bc,003Bh		; подкл. 1-ю страницу в 3-е окно
	rst     10h
	jp	c,llerr_dss_after_path
	; аксель
	ld      hl,0C000h
	di
	ld      d,d			; вкл. аксель на уст. размера блока
	ld      a,0			; блок 256 байт
	ld      b,b			; выкл. аксель
	ld      c,c			; заполнение блока
	ld      (hl),a			;
	ld      b,b			; выкл. аксель
	ei
	ld      hl,lib_table		; таблица библ
	ld      b,max_count		; макс. число загр. библиотек
ll5:	ld      a,(hl)
	or      a
	jr      z,ll5c
	push    hl
	pop     ix			; адрес в таблице библ
	ld      h,0C0h
	ld      l,(ix+1)
	ld      a,(ix+3)
	and     3Fh
	inc     a
	cp      (hl)
	jr      c,ll5a
	ld      (hl),a
ll5a:	push    ix
	pop     hl
ll5c:	inc     hl
	inc     hl
	inc     hl
	inc     hl
	djnz	ll5
	ld      hl,lib_table		; таблица библ
	ld      b,max_count		; макс. число загр. библиотек
	IFDEF	LIBMAN_DIAGNOSTICS
	ld	a,LS_TARGET
	ld	(ll_load_stage_active),a
	ENDIF
ll5b:	ld      a,(hl)
	or      a
	jr      z,ll6
	inc     hl
	inc     hl
	inc     hl
	inc     hl
	djnz	ll5b
	jp      llerr_after_path	; ошибка
	;
ll6:	push    hl
	pop     ix			; адрес в таблице
	ld	(ll_entry_ptr),hl
	; просканировать таблицу
	ld      hl,0C000h
	ld      bc,256			; размер таблицы
ll7:	ld      a,(hl)
	or      a
	jr      nz,ll8			; занятая запись
ll7a:	inc     hl
	dec     bc
	ld      a,b
	or      c
	jr      nz,ll7
	; выделить блок в 1-ну страницу
	ld      bc,013Dh
	rst     10h
	jp      c,llerr_dss_after_path	; ошибка выделения
	ld      l,a
	ld	a,true
	ld	(ll_final_new),a
	ld	a,(llsize+1)
	ld      d,0
	jr      ll8c
	;
ll8:	ld      d,a
	ld      a,(llsize+1)		; ст.байт размера библы
	add     a,d
	cp      40h			; (40)00
	jr      nc,ll7a
ll8c:	ld      e,a
	pop	af			; целевое окно из входного стека
	push	af
	; A = окно (1,2,3)
	dec	a			; a=1 ?
	jr      nz,ll8a
	ld      a,40h			; (40)00	page 1
	jr      ll9
ll8a:	dec	a			; a=2 ?
	jr      nz,ll8b
	ld      a,80h			; (80)00	page 2
	jr      ll9
ll8b:	ld      a,0C0h			; (C0)00	page 3
ll9:	ld	c,a
	add     a,d
	ld      d,a
	ld	a,c			; восст."a"
	add     a,e
	ld      e,a
	ld      (ix+0),true		; флаг "занятый элемент" в таблице
	ld      (ix+1),l		; дескр. страницы библы
	ld      (ix+2),d		; ст.байт адреса начала библы
	ld      (ix+3),e		; ст.байт адреса конца библы
	IFDEF	LIBMAN_L2_ONLY
	jp	ll_l2_finish		; единственный формат в этой сборке
	ELSE
	IFNDEF	LIBMAN_L0_L1_ONLY
ll2_active:	ld	a,false			; флаг "эта загрузка -- L2"
	or	a
	jp	nz,ll_l2_finish
	ENDIF
	push	de
	ld      a,(llid)		; дескр. выдел. блока из 2-х страниц
	ld      bc,013Bh		; подкл. 2-ю страницу в 3-е окно
	rst     10h
	pop	bc			; новый адрес кода
	jp	c,llerr_dss_with_entry
	; Estex-DSS may clobber IY.  Rebuild the relocation-table pointer from
	; the now-mapped canonical header immediately before remake instead of
	; carrying IY across allocation/mapping DSS calls.
	ld	hl,0C004h
	ld	e,(hl)
	inc	hl
	ld	d,(hl)
	push	de
	pop	iy
	ld	de,0C000h
	add     iy,de			; начало рел-таблицы + 0C000h
	ld	hl,0C000h		; адрес исходного кода
l1_form:ld	a,true			; флаг формата библы
	or	a
	jr	z,nofix			; "L0" формат
	; "L1" формат
	ld	de,32			; длина заголовка
	add	hl,de			; скоррект. начало исх. кода
nofix:	ld      de,(llsize)		; длина кода (размер библы)
	ld	a,(ll_fr+1)		; флаг релокации
	IFDEF	LIBMAN_CALL_TRACE
	ld	(l_trace_reloc_flag),a
	ld	a,b
	ld	(l_trace_reloc_base),a
	ld	a,(iy+4)
	ld	(l_trace_bitmap),a
	ld	a,(ll_fr+1)
	ENDIF
	or	a
	call	nz,remake		; настроить переходы
	IFDEF	LIBMAN_CALL_TRACE
	ld	hl,0C020h
	ld	a,(hl)
	ld	(l_trace_relocated+0),a
	inc	hl
	ld	a,(hl)
	ld	(l_trace_relocated+1),a
	inc	hl
	ld	a,(hl)
	ld	(l_trace_relocated+2),a
	ENDIF
	ENDIF				; !LIBMAN_L2_ONLY (staging is format-specific)

; Перенос готового образа из 2-й страницы временного блока в целевую.
; Оба формата приходят сюда с одним состоянием: отрелоцированный код лежит
; по 0C000h во 2-й странице временного блока, WIN3 подключён к ней же.
; Единственное место в загрузчике, которое чередует WIN3 между двумя разными
; дескрипторами, и единственное, чья работа подтверждена на реальном железе,
; поэтому L2 пользуется им как есть, а не своей копией (см. docs/l2_plan.md).
ll_copy_to_target:
	ld      hl,0C000h
	ld      a,(ix+2)
	or      0C0h
	ld      d,a
	ld      e,0
ll10:	push    de
	ld      de,llbuf		; буфер первых 16-ти байт заголовка
	IFDEF	LIBMAN_TEST_NO_ACCELERATOR
	; Тестовая подстановка: тот же перенос 16 байт и те же значения
	; регистров на выходе, но обычным LDIR.  Эмулятор исполняет идиому
	; акселя как однобайтный LD, поэтому без замены ll10 переносил бы
	; в тестах 1 байт из 16 и выдавал мусорную страницу за успешную
	; загрузку (см. tests/fixtures/libman_l2_vectors.asm).
	push	hl
	push	de
	push	bc
	ld	bc,16
	ldir
	pop	bc
	pop	de
	pop	hl
	ELSE
	; аксель
	di
	ld      d,d			; вкл. аксель на уст. размера блока
	ld      a,16			; размер буфера
	ld      b,b			; выкл. аксель
	ld      l,l			; копир. блока
	ld      a,(hl)			;
	ld      (de),a			;
	ld      b,b			; выкл. аксель
	ei
	ENDIF
	pop     de
	push    hl
	push	de
	IFDEF	LIBMAN_CALL_TRACE
	ld	a,5
	ld	(l_trace_l2_point),a
	ENDIF
	ld      a,(ix+1)		; дескр. блока из 2-х страниц
	IFDEF	LIBMAN_CALL_TRACE
	ld	(l_trace_l2_a),a
	ENDIF
	ld      bc,003Bh		; подкл. 1-ю страницу в 3-е окно
	rst     10h
	pop	de
	jp	c,llcopy_map_final_error
	ld      hl,llbuf		; буфер первых 16-ти байт заголовка
	IFDEF	LIBMAN_TEST_NO_ACCELERATOR
	; Тестовая подстановка: тот же перенос 16 байт и те же значения
	; регистров на выходе, но обычным LDIR.  Эмулятор исполняет идиому
	; акселя как однобайтный LD, поэтому без замены ll10 переносил бы
	; в тестах 1 байт из 16 и выдавал мусорную страницу за успешную
	; загрузку (см. tests/fixtures/libman_l2_vectors.asm).
	push	hl
	push	de
	push	bc
	ld	bc,16
	ldir
	pop	bc
	pop	de
	pop	hl
	ELSE
	; аксель
	di
	ld      d,d			; вкл. аксель на уст. размера блока
	ld      a,16			; размер буфера
	ld      b,b			; выкл. аксель
	ld      l,l			; копир. блока
	ld      a,(hl)			;
	ld      (de),a			;
	ld      b,b			; выкл. аксель
	ei
	ENDIF
	push	de
	IFDEF	LIBMAN_CALL_TRACE
	ld	a,6
	ld	(l_trace_l2_point),a
	ENDIF
	ld      a,(llid)		; дескр. выдел. блока из 2-х страниц
	IFDEF	LIBMAN_CALL_TRACE
	ld	(l_trace_l2_a),a
	ENDIF
	ld      bc,013Bh		; подкл. 2-ю страницу в 3-е окно
	rst     10h
	pop	de
	pop     hl
	jp	c,llerr_dss_with_entry
	ld      bc,16			; размер буфера
	add     hl,bc
	ex      de,hl
	add     hl,bc
	ex      de,hl
	; d only grows from the loop's starting value, so d=0 unambiguously
	; means it wrapped past the top of the address space: without this
	; guard a library ending exactly on the last byte of a page (d=FFh
	; wrapping to 00h) makes "cp d" true for every d and the loop never
	; terminates, overwriting all of RAM 16 bytes at a time.
	ld	a,d
	or	a
	jr	z,ll10_end
	ld      a,(ix+3)
	or      0C0h
	cp      d
	jr      nc,ll10
ll10_end:
	IFDEF	LIBMAN_CALL_TRACE
	ld	a,7
	ld	(l_trace_l2_point),a
	ENDIF
ll_finish_common:
	ld      a,(ix+1)		; дескр. целевой страницы
	ld      bc,003Bh		; подкл. 1-ю страницу в 3-е окно
	rst     10h
	jp	c,llerr_dss_with_entry
	IFDEF	LIBMAN_DIAGNOSTICS
	ld	a,LS_CLEANUP
	ld	(ll_load_stage_active),a
	ENDIF
	ld      a,(llid)		; дескр. выдел. блока из 2-х страниц
	ld      c,3Eh			; освободить блок памяти
	rst     10h
	jp	c,llerr_dss_with_entry	; ошибка освобождения
	xor	a
	ld	(ll_tmp_owned),a
	ld	hl,(ll_entry_ptr)
	ld      bc,lib_table		; таблица библ
	or	a
	sbc     hl,bc
	ld      a,l
	rra				; 2-й бит (4-ки) на место 0-го
	rra				; адрес ячейки в таблице библ -> в номер дескр.
	ld      l,a			; номер дескр. загр. библы
	ld      h,0
	ld      b,h			; 0-й номер функции
	IFDEF	LIBMAN_DIAGNOSTICS
	ld	a,LS_INIT
	ld	(ll_load_stage_active),a
	ENDIF
lloldw:	ld      a,-1			; сохр. начальная Page3
	out     (0E2h),a		; восст. страницу
	ld	a,(llhand)		; documented open file handle for DLL INIT
	call    corecall		; иниц. (загрузить) библу
	IFDEF	LIBMAN_DIAGNOSTICS
	call	c,ll_record_init_failure
	ENDIF
	push	af
	push	hl
	IFDEF	LIBMAN_DIAGNOSTICS
	ld	a,LS_CLEANUP
	ld	(ll_load_stage_active),a
	ENDIF
	call	ll_close_file
	call	c,ll_record_dss_error
	jp	c,ll_close_error
	pop	hl
	pop	af
	jp	c,ll_init_error
	pop	bc			; удалить сохраненное целевое окно
	pop	de
	pop	iy
	pop	ix
	ret

	IFNDEF	LIBMAN_L0_L1_ONLY
;==================================================================
;  L2: header+code (up to a full 16 KiB page) and the relocation
;  table are never RLE-compressed, so the packed-prefix bounce-copy
;  loop above does not apply.  Validate the header fields directly,
;  then feed the shared page-sharing allocator (ll4a) exactly as
;  L0/L1 do; ll_l2_finish reads code straight into the target page
;  and relocates it in chunks against a temp-page copy of the table.
;
;  This block lives past the loader's success path so the L0/L1
;  branch keeps falling straight through into ll_fr/ll4a as in 1.3.
;==================================================================
; Куда читается таблица перемещений L2 в 1-й странице временного блока.
; Ниже неё лежат буфер пути (до 0C110h при ёмкости по умолчанию) и
; 256-байтовая карта занятости страниц 0C000h..0C0FFh, которую заполняет
; ll4a и заполняет/сканирует ll5/ll7.  Таблица ограничена 2044 байтами и
; укладывается в 16 KiB страницы с большим запасом.
ll2_table_page	equ	0C200h

; Out: CF=0 when hl <= 4000h, CF=1 otherwise.  hl preserved, de clobbered.
; Used for both code_size and reloc_size: since each is independently bounded
; to <=4000h, their later sum cannot overflow 16 bits.  The verdict comes back
; in CF instead of jumping to the error handler directly: the callers own stack
; entries (l_load's saved registers, a pushed code_size) that llerr_after_path
; unwinds by count, so a call that never returns would desynchronize it.
ll2_check_page_limit:
	ld	de,4000h
	ex	de,hl
	or	a
	sbc	hl,de			; 4000h - value
	ex	de,hl			; hl restored; CF=1 when value > 4000h
	ret

ll_l2_entry:
	ld	l,(ix+4)		; code_size, мл./ст.байт
	ld	h,(ix+5)
	ld	a,l
	sub	32
	ld	a,h
	sbc	a,0
	jp	c,llerr_after_path	; code_size < 32: переполнит ll2_left ниже
	call	ll2_check_page_limit
	jp	c,llerr_after_path	; code_size > 4000h
	ld	c,(ix+6)		; reloc_size, мл./ст.байт
	ld	b,(ix+7)
	ld	a,b
	or	c
	jr	z,ll2_not_relocatable
	ld	a,true
	ld	(ll_fr+1),a
	push	hl			; сохр. code_size
	ld	h,b
	ld	l,c
	call	ll2_check_page_limit
	pop	hl			; pop не трогает флаги
	jp	c,llerr_after_path	; reloc_size > 4000h
	jr	ll2_reloc_checked
ll2_not_relocatable:
	xor	a
	ld	(ll_fr+1),a
ll2_reloc_checked:
	ld	e,(ix+2)		; file_size, мл./ст.байт
	ld	d,(ix+3)
	push	hl			; сохр. code_size
	add	hl,bc			; hl = code_size + reloc_size (не переполн.)
	or	a
	sbc	hl,de
	pop	hl			; pop не трогает флаги
	jp	nz,llerr_after_path	; L2 не бывает сжатой: file_size обязан
					; равняться code_size+reloc_size
	IFNDEF	LIBMAN_L2_ONLY
	ld	a,true
	ld	(ll2_active+1),a
	ENDIF
	ld	hl,(llsize)		; измеренный физич. размер файла
	or	a
	sbc	hl,de
	jp	c,llerr_after_path	; файл короче заявленного prefix

	; Образ читается здесь, а не в хвосте загрузки, чтобы у L2 сохранялся
	; инвариант исторического пути: НИ ОДНОГО DSS READ после выделения
	; целевой страницы.  На реальном железе нарушение этого порядка делает
	; свежий дескриптор целевой страницы непригодным -- первый же SETWIN3
	; на него возвращает CF=1/A=0 (подтверждено трассировкой: чтения
	; проходят, падает SETWIN3 в ll10).  ll0 у L0/L1 читает ровно в этой
	; точке: временная страница подключена, целевая ещё не выделена.
	; Порядок чтений совпадает с порядком в файле (код, затем таблица):
	; DSS READ последовательный, без seek, и после второго чтения файловый
	; указатель стоит ровно на trailing payload, который ждёт INIT.
	;
	; Поля заголовка берутся по абсолютному адресу, а не через (ix+n):
	; DSS READ не сохраняет ix.  Исторический путь этого не замечает --
	; он вычитывает заголовок в регистры до своего единственного чтения и
	; наводит ix на буфер уже после него.  Обращение к (ix+n) после READ
	; даёт мусор: на железе это вылезло как случайная длина таблицы и
	; файловый указатель, уехавший за конец файла (init=E2).
	ld	a,(llid)
	ld	bc,013Bh		; код -- во 2-ю страницу временного блока
	rst	10h
	jp	c,llerr_dss_after_path
	ld	de,(llbuf+4)		; de = code_size (вместе с заголовком)
	ld	hl,0C000h
	ld	bc,0013h		; C=13h: READ.  B не задействован, задан явно
	ld	a,(llhand)
	rst	10h
	jp	c,llerr_dss_after_path	; ошибка чтения кода
	ld	a,(ll_fr+1)
	or	a
	jr	z,ll2_image_read	; таблицы нет -- читать нечего
	ld	a,(llid)
	ld	bc,003Bh		; таблица -- в 1-ю страницу, мимо карты
	rst	10h
	jp	c,llerr_dss_after_path
	ld	de,(llbuf+6)		; de = reloc_size
	ld	hl,ll2_table_page
	ld	bc,0013h		; C=13h: READ.  B не задействован, задан явно
	ld	a,(llhand)
	rst	10h
	jp	c,llerr_dss_after_path	; ошибка чтения таблицы
ll2_image_read:
	ld	hl,(llbuf+4)		; hl = code_size
	ld	a,(ll_fr+1)
	or	a
	jr	nz,ll2_relocatable
	; Не перемещаемая библа обязана занять свежую страницу
	; целиком (см. ll8).  3FFFh -- инклюзивный конец страницы,
	; как и code_size-1 ниже: 4000h завернул бы (ix+3) через
	; 100h, и скан ll5 посчитал бы страницу почти свободной,
	; разрешив подселение поверх загруженной библы.
	ld	hl,3FFFh
	jp	ll4a
ll2_relocatable:
	dec	hl			; hl = code_size - 1 (та же формула, что у L0/L1)
	jp	ll4a

;==================================================================
;  L2 tail: (ix+1)=дескр. целевой страницы, (ix+2)/(ix+3)=ст.байты
;  начала/конца в целевом окне (см. ll9).
;
;  Код и таблица уже прочитаны (см. ll_l2_entry): код лежит по 0C000h во
;  2-й странице временного блока, таблица -- по ll2_table_page в 1-й, за
;  256-байтовой картой страниц, которой пользуются ll5/ll7.  Здесь остаётся
;  только релокация, и она не делает ни одного DSS-вызова кроме SETWIN3
;  между двумя страницами ОДНОГО дескриптора -- ровно то чередование,
;  которым пользуется распаковщик L0/L1 (loop:).  Дальше образ переносится
;  в целевую страницу общим циклом ll10 (ll_copy_to_target).
;
;  Вход: WIN3 = 1-я страница временного блока (её подключил ll4a), то есть
;  таблица уже видна; выход в ll_copy_to_target -- всегда со 2-й страницей,
;  которую ll10 и ожидает увидеть как источник.
;==================================================================
ll_l2_finish:
	IFDEF	LIBMAN_DIAGNOSTICS
	ld	a,LS_COPY
	ld	(ll_load_stage_active),a
	ENDIF
	ld	a,(ll_fr+1)
	or	a
	jp	z,ll2_map_code		; не перемещаемая: править нечего
	ld	hl,(llbuf+4)		; code_size из копии заголовка
	ld	de,-32
	add	hl,de			; hl = размер тела (код без заголовка)
	ld	a,h
	or	l
	jp	z,ll2_map_code		; тело пустое, remake зациклился бы на de=0
	ld	(ll2_left),hl
	ld	hl,0C020h		; тело во 2-й странице, сразу за заголовком
	ld	(ll2_code_addr),hl
	ld	hl,ll2_table_page
	ld	(ll2_table_addr),hl

; Каждая итерация входит с подключённой 1-й страницей (таблица) и выходит
; либо с ней же -- на следующий чанк, либо со 2-й (код) -- наружу, в ll10.
ll2_chunk:
	ld	hl,(ll2_left)
	ld	de,128
	or	a
	sbc	hl,de
	jr	c,ll2_chunk_partial
	ld	(ll2_left),hl		; остаток -= 128
	ld	hl,128
	ld	(ll2_chunk_size),hl
	jr	ll2_chunk_table
ll2_chunk_partial:
	add	hl,de			; hl = исходный остаток (< 128, отменить заём)
	ld	(ll2_chunk_size),hl
	ld	hl,0
	ld	(ll2_left),hl
ll2_chunk_table:
	ld	hl,(ll2_table_addr)
	ld	de,llbuf		; буфер первых 16-ти байт заголовка
	ld	bc,16
	ldir				; ldir оставляет hl = источник+16
	ld	(ll2_table_addr),hl
	IFDEF	LIBMAN_CALL_TRACE
	ld	a,3
	ld	(l_trace_l2_point),a
	ENDIF
	ld	a,(llid)
	IFDEF	LIBMAN_CALL_TRACE
	ld	(l_trace_l2_a),a
	ENDIF
	ld	bc,013Bh		; подкл. 2-ю страницу (код) в 3-е окно
	rst	10h
	jp	c,llerr_dss_with_entry
	ld	hl,(ll2_code_addr)
	ld	de,(ll2_chunk_size)
	ld	iy,llbuf
	ld	a,(ix+2)
	ld	b,a			; дельта для remake (см. remake: ld c,b)
	call	remake
	ld	(ll2_code_addr),hl	; remake оставляет hl за концом чанка
	ld	hl,(ll2_left)
	ld	a,h
	or	l
	jp	z,ll_copy_to_target	; всё готово, WIN3 = страница кода
	IFDEF	LIBMAN_CALL_TRACE
	ld	a,4
	ld	(l_trace_l2_point),a
	ENDIF
	ld	a,(llid)
	IFDEF	LIBMAN_CALL_TRACE
	ld	(l_trace_l2_a),a
	ENDIF
	ld	bc,003Bh		; обратно на 1-ю страницу (таблица)
	rst	10h
	jp	c,llerr_dss_with_entry
	jr	ll2_chunk

ll2_map_code:
	IFDEF	LIBMAN_CALL_TRACE
	ld	a,2
	ld	(l_trace_l2_point),a
	ENDIF
	ld	a,(llid)
	IFDEF	LIBMAN_CALL_TRACE
	ld	(l_trace_l2_a),a
	ENDIF
	ld	bc,013Bh		; подкл. 2-ю страницу (код) в 3-е окно
	rst	10h
	jp	c,llerr_dss_with_entry
	jp	ll_copy_to_target
	ENDIF				; !LIBMAN_L0_L1_ONLY (L2 entry and tail)

ll_init_error:
	push	af
	call	corefree		; выгрузить библу
	jr	c,ll_init_free_error
	xor	a
	ld	(ll_final_new),a
ll_init_free_error:
	call	ll_clear_entry
	call	ll_cleanup_no_file
	pop	af
	pop	bc			; удалить сохраненное целевое окно
	pop	de
	pop	iy
	pop	ix
	ret

; ll10 is shared by both formats now, so its unwind must exist in every build.
llcopy_map_final_error:
	pop	hl			; снять сохраненный адрес источника
	jr	llerr_dss_with_entry

ll_close_error:
	pop	hl			; handle
	pop	af			; результат init больше не возвращается
	call	corefree
	jr	c,ll_close_free_error
	xor	a
	ld	(ll_final_new),a
ll_close_free_error:
	call	ll_clear_entry
	call	ll_cleanup_partial
	jr	llerr_return

llerr_dss_with_entry:
	call	ll_record_dss_error
llerr_with_entry:
	call	ll_clear_entry
	jr	llerr_after_path

ll_clear_entry:
	ld	ix,(ll_entry_ptr)
	xor	a
	ld	(ix+0),a
	ret

	IFNDEF	LIBMAN_L2_ONLY
ll_decode_error:
	pop	hl			; discard saved packed-source pointer
	jp	llerr_after_path
	ENDIF

llerr_dss_before_path:
	call	ll_record_dss_error
	jr	llerr_before_path
llerr_before_path:
	pop	hl			; имя еще находилось в стеке
	jr	llerr_no_file_after_path
llerr_dss_after_path:
	call	ll_record_dss_error
llerr_after_path:
	IFDEF	LIBMAN_DIAGNOSTICS
	call	ll_record_loader_stage
	ENDIF
	call	ll_cleanup_partial
	jr	llerr_return
llerr_no_file_after_path:
	IFDEF	LIBMAN_DIAGNOSTICS
	call	ll_record_loader_stage
	ENDIF
	call	ll_cleanup_no_file
llerr_return:
	pop	bc			; удалить сохраненное целевое окно
	pop	de
	pop	iy
	pop	ix
	scf
	ld	a,-1
	ret

	ENDIF				; !LIBMAN_RUNTIME_ONLY


	IFNDEF	LIBMAN_LOADER_ONLY

corefree equ	_L_FREE
corecall equ	_L_CALL
coreinfo equ	_L_INFO



;==================================================================
;  Коррекция адресов переходов по таблице перемещений
;==================================================================
; de = длина кода
; bc = новый адрес кода (b=старший байт)
; hl = адрес коррект. кода
; iy = начало рел-таблицы
;
remake:	ld	c,b
rmk1:	ld	b,8			; разрядность байта
	ld	a,(iy+0)
rmk2:	rla
	call	c,reloc			; правка ст.байта адреса
	ex	af,af'
	inc	hl
	dec	de
	ld	a,d
	or	e
	ret	z
	ex	af,af'
	djnz	rmk2
	inc	iy
	jr	rmk1
	;
reloc:	ex	af,af'
	ld	a,(hl)
	add	a,c
	ld	(hl),a
	ex	af,af'
	ret





;==================================================================
;  Выгрузка библиотеки из памяти
;==================================================================
;
;    ld      hl,(handle)
;    call    l_free
;    jp      c,error
;
_L_FREE:
	push	de
	push	bc
	ld      b,1			; номер функции
	call    corecall
	;ld      d,0
	;ld      e,l
	ex	de,hl			; поставил
	ld      hl,lib_table		; таблица библ
	add     hl,de
	add     hl,de
	add     hl,de
	add     hl,de
	ld      a,(hl)			; +0 свободна/занята
	or      a
	scf
	jr      z,lf_ee
	ld      (hl),0
	inc     hl
	ld      c,(hl)			; +1 дескр. окна
	ld      hl,lib_table		; таблица библ
	ld      b,max_count		; макс. число загр. библиотек
	ld      e,0
lf1:	ld      a,(hl)
	or	a			; LD не обновляет Z: проверить флаг занятости явно
	jr      z,lf2
	inc     hl
	ld      a,(hl)
	cp      c
	jr      nz,lf3
	inc     e
	jr      lf3
	;
lf2:	inc     hl
lf3:	inc     hl
	inc     hl
	inc     hl
	djnz	lf1
	ld      a,e
	or      a
	jr      nz,lf_e
	ld      a,c			; дескр. блока
	ld      c,3Eh			; освободить блок
	rst     10h
	jr	lf_ee
	;
lf_e:	xor     a
lf_ee:	pop	bc
	pop	de
	ret




;==================================================================
;  Вызов процедур библиотеки на исполнение
;==================================================================
; Передаваемые параметры в: a,de,ix,iy and alt. regs
; C = физическая страница, вытесненная DLL из целевого окна
;
;    ld      hl,(handle)  ;дескр. библы
;    ld      b,function   ;номер функции
;    call    l_call
;    jp      c,error
;
;    out: hl=handle
;
_L_CALL:
	push    hl
	push    de
	push    bc
	push    af
	xor	a
	ld	(lcflag),a
	ld	a,b			; номер функции
	ld	(lc_fun),a
	ld      a,l			; дескр. библы
	add	a,a			; handle * 4, независимо от входного CF
	add	a,a
	ld      l,a
	ld      de,lib_table		; таблица библ
	add     hl,de			; перейти на адрес элемента таблицы
	ld      a,(hl)			; +0 ячейка занятости
	or      a
	jp      z,lc_er2		; ошибка, элемент не занят
	inc     hl
	ld      a,(hl)			; +1 дескр. блока памяти
	push    af
	inc     hl
	ld      h,(hl)			; +2 ст.байт адрес начала
	ld      l,20h			; смещ. на размер заголовка
	ld      (lcstart),hl		; начало кода библы в окне
	ld      a,h
	and     0C0h
	ld      (lcoldp),a
	cp      40h
	jr      nz,lc1
	in      a,(0A2h)
	jr      lc3
	;
lc1:	cp      80h
	jr      nz,lc2
	in      a,(0C2h)
	jr      lc3
	;
lc2:	cp      0C0h
	IFDEF	LIBMAN_CALL_TRACE
	jp      nz,lc_er3
	ELSE
	jr      nz,lc_er3
	ENDIF
	in      a,(0E2h)
lc3:	ld      (lc4_+1),a
	; Generic DSS SETWIN (#38) is broken in current Estex-DSS for WIN1:
	; select SETWIN1/2/3 (#39..#3B) from the window bits in H.
	ld	a,h
	rlca
	rlca
	and	3
	add	a,38h
	ld	c,a
	ld	b,0			; первая страница блока DLL
	pop     af			; дескр. блока памяти (из +1)
	push	ix
	push	iy
	rst     10h
	jr	nc,lc_setwin_ok
	IFDEF	LIBMAN_DIAGNOSTICS
	push	af
	ld	(lc_dss_error),a
	ld	a,true
	ld	(lcflag),a
	pop	af
	ENDIF
	pop	iy
	pop	ix
	jr	lc_er2
lc_setwin_ok:
	IFDEF	LIBMAN_CALL_TRACE
	ld	a,(lc_fun)
	or	a
	jr	nz,lc_trace_done
	ld	(l_trace_function),a
	ld	hl,(lcstart)
	ld	a,(hl)
	ld	(l_trace_mapped+0),a
	inc	hl
	ld	a,(hl)
	ld	(l_trace_mapped+1),a
	inc	hl
	ld	a,(hl)
	ld	(l_trace_mapped+2),a
lc_trace_done:
	ENDIF
	pop	iy
	pop	ix
	pop     af
	pop     bc
	pop     de
	; возможные передаваемые
	; аргументы функции:
	; a,de,ix,iy and alt. regs; c=предыдущая физическая страница окна
	ld      hl,(lcstart)		; начало кода библы в окне
	ld      c,b			; номер передаваемой функции
	ld      b,0
	add     hl,bc			;1+1=2 обойти init, free (0,1) функции
	add     hl,bc			;2+1=3
	add     hl,bc			;3+1=4
	ld      bc,lc_
	push    bc			; в стек точку возврата
	ld	bc,(lc4_+1)		; c=страница окна до подключения DLL; b не определен
	jp      (hl)			; Вызов функции

lc_:	pop     hl			; восст. вход. дескриптор (и баланс стека)
	ld	c,a			; сохр."a"
	jr	nc,lc4_
	ld	a,(lc_fun)
	or	a			; тест на 0-ю функцию
	jr	nz,lc4_
	dec	a			; a=0FFh
	ld	(lcflag),a
lc4_:	ld      a,-1
	ld      b,a
	ld      a,(lcoldp)
	cp      40h
	jr      nz,lc1_
	ld      a,b
	out     (0A2h),a
	jr      lc3_
	;
lc1_:	cp      80h
	jr      nz,lc2_
	ld      a,b
	out     (0C2h),a
	jr      lc3_
	;
lc2_:	cp      0C0h
	jr      nz,lc_er0
	ld      a,b
	out     (0E2h),a
lc3_:	ld	a,(lcflag)
	rlca				; уст. carry-флаг
	ld	a,c			; восст."a"
	ret
	;
lc_er3:	pop     af
lc_er2:	pop     af
	pop     bc
	pop     de
lc_er1:	pop     hl
lc_er0:	scf
	ret


;==================================================================
;  Получить информацию о библиотеке
;==================================================================
; copy lib info to buffer
;
;    ld      hl,(handle)    ;дескр. библы
;    ld      de,buffer32    ;буфер, 32 байта
;    call    l_info
;    jp      c,error
;
_L_INFO:
	push    hl
	push    de
	push    bc
	ld      a,l
	add	a,a			; handle * 4, независимо от входного CF
	add	a,a
	ld	l,a
	ld      bc,lib_table		; таблица библ
	add     hl,bc
	ld      a,(hl)			;+0 флаг "свободна/занята"
	or      a
	scf
	jr      z,li_er			; ошибка
	inc     hl
	ld      b,(hl)			;+1 дескр. страницы библы
	inc     hl
	ld      a,(hl)
	or      0C0h
	ld      h,a
	ld      l,0
	in      a,(0E2h)
	ld      (lioldw+1),a
	push	hl			; Estex-DSS SETWIN3 может менять HL/DE
	push	de
	ld      a,b			; дескр. страницы библы
	ld      bc,003Bh		; подкл. в 3-е окно
	rst     10h
	pop	de
	pop	hl
	jr	c,li_map_error
	ld      bc,32			; длина info
	ldir
lioldw:	ld	a,-1			; восст. порт
	out	(0E2h),a
	xor	a
	jr	li_er
li_map_error:
	push	af
	ld	a,(lioldw+1)
	out	(0E2h),a
	pop	af
	scf
li_er:	pop	bc
	pop	de
	pop	hl
	ret

	ENDIF				; !LIBMAN_LOADER_ONLY
