; Generated by scripts/export_z80asm.py; do not edit.
; Source of truth: the sibling canonical SjASMPlus export.
; Compatibility include name for projects that used a vendored libman13.asm.
        INCLUDE "libman.asm"
